# Generated by Django 2.0.2 on 2018-02-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('posted_date', models.DateField()),
                ('added_in_db_date', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField()),
                ('isSent', models.BooleanField(default=False)),
            ],
        ),
    ]
