# Generated by Django 2.0.1 on 2018-01-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('posted_date', models.DateField()),
                ('added_in_db_date', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField()),
            ],
        ),
    ]
